// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship['fields'][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship['id']]: ContentRelationshipFieldWithData<
      TSubRelationship['customtypes'],
      TLang
    >;
  } & { // Group
    [TGroup in Extract<
      TRelationship['fields'][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup['id']]: TData[TGroup['id']] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & { // Other fields
    [TFieldKey in Extract<
      TRelationship['fields'][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >['id']]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>['data'],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>['id']];

type EmployersRecruitersDocumentDataSlicesSlice = never;

/**
 * Content for Employers and Recruiters documents
 */
interface EmployersRecruitersDocumentData {
  /**
   * title field in *Employers and Recruiters*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: employers_recruiters.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * body field in *Employers and Recruiters*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: employers_recruiters.body
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * `slices` field in *Employers and Recruiters*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: employers_recruiters.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<EmployersRecruitersDocumentDataSlicesSlice>;
}

/**
 * Employers and Recruiters document from Prismic
 *
 * - **API ID**: `employers_recruiters`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EmployersRecruitersDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<EmployersRecruitersDocumentData>,
    'employers_recruiters',
    Lang
  >;

type HomepageDocumentDataSlicesSlice = never;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Introduction field in *Homepage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.introduction
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  introduction: prismic.RichTextField;

  /**
   * `slices` field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    'homepage',
    Lang
  >;

type ResumeDocumentDataBodySlice =
  | LinksSlice
  | ResumeContentSlice
  | ResumeListSlice
  | ResumeWorkHistorySlice
  | ResumeWorkHistoryCondensedSlice
  | ResumeAwardsSlice
  | WorkTogetherSlice
  | ResumeEducationSlice;

/**
 * Content for Resume documents
 */
interface ResumeDocumentData {
  /**
   * Name field in *Resume*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: resume.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  name: prismic.RichTextField;

  /**
   * Current Job Title field in *Resume*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: resume.current_job_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  current_job_title: prismic.RichTextField;

  /**
   * Current Role Location field in *Resume*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: resume.current_role_location
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  current_role_location: prismic.RichTextField;

  /**
   * Slice Zone field in *Resume*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: resume.body[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  body: prismic.SliceZone<ResumeDocumentDataBodySlice>;
}

/**
 * Resume document from Prismic
 *
 * - **API ID**: `resume`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ResumeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ResumeDocumentData>,
    'resume',
    Lang
  >;

export type AllDocumentTypes =
  | EmployersRecruitersDocument
  | HomepageDocument
  | ResumeDocument;

/**
 * Primary content in *Links → Default → Primary*
 */
export interface LinksSliceDefaultPrimary {
  /**
   * Title field in *Links → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Links.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;
}

/**
 * Primary content in *Links → Items*
 */
export interface LinksSliceDefaultItem {
  /**
   * label field in *Links → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Links.items[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * link field in *Links → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: Links.items[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * type field in *Links → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: Links.items[].type
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  type: prismic.SelectField<
    | 'website'
    | 'phone'
    | 'email'
    | 'document'
    | 'external'
    | 'project'
    | 'user'
    | 'user_plus'
    | 'users'
    | 'code'
    | 'command'
  >;
}

/**
 * Default variation for Links Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LinksSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<LinksSliceDefaultPrimary>,
  Simplify<LinksSliceDefaultItem>
>;

/**
 * Slice variation for *Links*
 */
type LinksSliceVariation = LinksSliceDefault;

/**
 * Links Shared Slice
 *
 * - **API ID**: `Links`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LinksSlice = prismic.SharedSlice<'Links', LinksSliceVariation>;

/**
 * Primary content in *ResumeAwards → Default → Primary*
 */
export interface ResumeAwardsSliceDefaultPrimary {
  /**
   * Title field in *ResumeAwards → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ResumeAwards.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;
}

/**
 * Primary content in *ResumeAwards → Items*
 */
export interface ResumeAwardsSliceDefaultItem {
  /**
   * Title field in *ResumeAwards → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ResumeAwards.items[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Dates field in *ResumeAwards → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ResumeAwards.items[].dates
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  dates: prismic.KeyTextField;
}

/**
 * Default variation for ResumeAwards Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ResumeAwardsSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<ResumeAwardsSliceDefaultPrimary>,
  Simplify<ResumeAwardsSliceDefaultItem>
>;

/**
 * Slice variation for *ResumeAwards*
 */
type ResumeAwardsSliceVariation = ResumeAwardsSliceDefault;

/**
 * ResumeAwards Shared Slice
 *
 * - **API ID**: `ResumeAwards`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ResumeAwardsSlice = prismic.SharedSlice<
  'ResumeAwards',
  ResumeAwardsSliceVariation
>;

/**
 * Primary content in *ResumeContent → Default → Primary*
 */
export interface ResumeContentSliceDefaultPrimary {
  /**
   * Title field in *ResumeContent → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ResumeContent.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Content field in *ResumeContent → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ResumeContent.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;

  /**
   * Large Copy field in *ResumeContent → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: ResumeContent.default.primary.large_copy
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  large_copy: prismic.BooleanField;

  /**
   * Include in Print field in *ResumeContent → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: ResumeContent.default.primary.include_in_print
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  include_in_print: prismic.BooleanField;
}

/**
 * Default variation for ResumeContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ResumeContentSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<ResumeContentSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ResumeContent*
 */
type ResumeContentSliceVariation = ResumeContentSliceDefault;

/**
 * ResumeContent Shared Slice
 *
 * - **API ID**: `ResumeContent`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ResumeContentSlice = prismic.SharedSlice<
  'ResumeContent',
  ResumeContentSliceVariation
>;

/**
 * Primary content in *ResumeEducation → Default → Primary*
 */
export interface ResumeEducationSliceDefaultPrimary {
  /**
   * Title field in *ResumeEducation → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ResumeEducation.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;
}

/**
 * Primary content in *ResumeEducation → Items*
 */
export interface ResumeEducationSliceDefaultItem {
  /**
   * Institution field in *ResumeEducation → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ResumeEducation.items[].institution
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  institution: prismic.RichTextField;

  /**
   * Copy field in *ResumeEducation → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ResumeEducation.items[].copy
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  copy: prismic.RichTextField;

  /**
   * Start Date field in *ResumeEducation → Items*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: ResumeEducation.items[].start_date
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  start_date: prismic.DateField;

  /**
   * End Date field in *ResumeEducation → Items*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: ResumeEducation.items[].end_date
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  end_date: prismic.DateField;
}

/**
 * Default variation for ResumeEducation Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ResumeEducationSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<ResumeEducationSliceDefaultPrimary>,
  Simplify<ResumeEducationSliceDefaultItem>
>;

/**
 * Slice variation for *ResumeEducation*
 */
type ResumeEducationSliceVariation = ResumeEducationSliceDefault;

/**
 * ResumeEducation Shared Slice
 *
 * - **API ID**: `ResumeEducation`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ResumeEducationSlice = prismic.SharedSlice<
  'ResumeEducation',
  ResumeEducationSliceVariation
>;

/**
 * Primary content in *ResumeList → Default → Primary*
 */
export interface ResumeListSliceDefaultPrimary {
  /**
   * Title field in *ResumeList → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ResumeList.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Content field in *ResumeList → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ResumeList.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;
}

/**
 * Primary content in *ResumeList → Items*
 */
export interface ResumeListSliceDefaultItem {
  /**
   * Content field in *ResumeList → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ResumeList.items[].content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for ResumeList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ResumeListSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<ResumeListSliceDefaultPrimary>,
  Simplify<ResumeListSliceDefaultItem>
>;

/**
 * Slice variation for *ResumeList*
 */
type ResumeListSliceVariation = ResumeListSliceDefault;

/**
 * ResumeList Shared Slice
 *
 * - **API ID**: `ResumeList`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ResumeListSlice = prismic.SharedSlice<
  'ResumeList',
  ResumeListSliceVariation
>;

/**
 * Primary content in *ResumeWorkHistory → Default → Primary*
 */
export interface ResumeWorkHistorySliceDefaultPrimary {
  /**
   * Title field in *ResumeWorkHistory → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ResumeWorkHistory.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;
}

/**
 * Primary content in *ResumeWorkHistory → Items*
 */
export interface ResumeWorkHistorySliceDefaultItem {
  /**
   * Company Logo field in *ResumeWorkHistory → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: ResumeWorkHistory.items[].company_logo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  company_logo: prismic.ImageField<never>;

  /**
   * Company field in *ResumeWorkHistory → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ResumeWorkHistory.items[].company
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  company: prismic.RichTextField;

  /**
   * Job Title field in *ResumeWorkHistory → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ResumeWorkHistory.items[].job_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  job_title: prismic.RichTextField;

  /**
   * Content field in *ResumeWorkHistory → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ResumeWorkHistory.items[].content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;

  /**
   * Present Role field in *ResumeWorkHistory → Items*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: ResumeWorkHistory.items[].present_role
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  present_role: prismic.BooleanField;

  /**
   * Start Date field in *ResumeWorkHistory → Items*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: ResumeWorkHistory.items[].start_date
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  start_date: prismic.DateField;

  /**
   * End Date field in *ResumeWorkHistory → Items*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: ResumeWorkHistory.items[].end_date
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  end_date: prismic.DateField;

  /**
   * Company Website field in *ResumeWorkHistory → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: ResumeWorkHistory.items[].company_website
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  company_website: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Keywords field in *ResumeWorkHistory → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ResumeWorkHistory.items[].keywords
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  keywords: prismic.KeyTextField;
}

/**
 * Default variation for ResumeWorkHistory Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ResumeWorkHistorySliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<ResumeWorkHistorySliceDefaultPrimary>,
  Simplify<ResumeWorkHistorySliceDefaultItem>
>;

/**
 * Slice variation for *ResumeWorkHistory*
 */
type ResumeWorkHistorySliceVariation = ResumeWorkHistorySliceDefault;

/**
 * ResumeWorkHistory Shared Slice
 *
 * - **API ID**: `ResumeWorkHistory`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ResumeWorkHistorySlice = prismic.SharedSlice<
  'ResumeWorkHistory',
  ResumeWorkHistorySliceVariation
>;

/**
 * Primary content in *ResumeWorkHistoryCondensed → Default → Primary*
 */
export interface ResumeWorkHistoryCondensedSliceDefaultPrimary {
  /**
   * Title field in *ResumeWorkHistoryCondensed → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ResumeWorkHistoryCondensed.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;
}

/**
 * Primary content in *ResumeWorkHistoryCondensed → Items*
 */
export interface ResumeWorkHistoryCondensedSliceDefaultItem {
  /**
   * Company field in *ResumeWorkHistoryCondensed → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ResumeWorkHistoryCondensed.items[].company
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  company: prismic.RichTextField;

  /**
   * Job Title field in *ResumeWorkHistoryCondensed → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ResumeWorkHistoryCondensed.items[].job_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  job_title: prismic.RichTextField;

  /**
   * Start Date field in *ResumeWorkHistoryCondensed → Items*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: ResumeWorkHistoryCondensed.items[].start_date
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  start_date: prismic.DateField;

  /**
   * End Date field in *ResumeWorkHistoryCondensed → Items*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: ResumeWorkHistoryCondensed.items[].end_date
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  end_date: prismic.DateField;
}

/**
 * Default variation for ResumeWorkHistoryCondensed Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ResumeWorkHistoryCondensedSliceDefault =
  prismic.SharedSliceVariation<
    'default',
    Simplify<ResumeWorkHistoryCondensedSliceDefaultPrimary>,
    Simplify<ResumeWorkHistoryCondensedSliceDefaultItem>
  >;

/**
 * Slice variation for *ResumeWorkHistoryCondensed*
 */
type ResumeWorkHistoryCondensedSliceVariation =
  ResumeWorkHistoryCondensedSliceDefault;

/**
 * ResumeWorkHistoryCondensed Shared Slice
 *
 * - **API ID**: `ResumeWorkHistoryCondensed`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ResumeWorkHistoryCondensedSlice = prismic.SharedSlice<
  'ResumeWorkHistoryCondensed',
  ResumeWorkHistoryCondensedSliceVariation
>;

/**
 * Primary content in *WorkTogether → Default → Primary*
 */
export interface WorkTogetherSliceDefaultPrimary {
  /**
   * Title field in *WorkTogether → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: WorkTogether.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Body: Yes field in *WorkTogether → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: WorkTogether.default.primary.body_yes
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body_yes: prismic.RichTextField;

  /**
   * Body: No field in *WorkTogether → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: WorkTogether.default.primary.body_no
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body_no: prismic.RichTextField;

  /**
   * note field in *WorkTogether → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: WorkTogether.default.primary.note
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  note: prismic.RichTextField;
}

/**
 * Default variation for WorkTogether Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type WorkTogetherSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<WorkTogetherSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *WorkTogether*
 */
type WorkTogetherSliceVariation = WorkTogetherSliceDefault;

/**
 * WorkTogether Shared Slice
 *
 * - **API ID**: `WorkTogether`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type WorkTogetherSlice = prismic.SharedSlice<
  'WorkTogether',
  WorkTogetherSliceVariation
>;

declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      EmployersRecruitersDocument,
      EmployersRecruitersDocumentData,
      EmployersRecruitersDocumentDataSlicesSlice,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      ResumeDocument,
      ResumeDocumentData,
      ResumeDocumentDataBodySlice,
      AllDocumentTypes,
      LinksSlice,
      LinksSliceDefaultPrimary,
      LinksSliceDefaultItem,
      LinksSliceVariation,
      LinksSliceDefault,
      ResumeAwardsSlice,
      ResumeAwardsSliceDefaultPrimary,
      ResumeAwardsSliceDefaultItem,
      ResumeAwardsSliceVariation,
      ResumeAwardsSliceDefault,
      ResumeContentSlice,
      ResumeContentSliceDefaultPrimary,
      ResumeContentSliceVariation,
      ResumeContentSliceDefault,
      ResumeEducationSlice,
      ResumeEducationSliceDefaultPrimary,
      ResumeEducationSliceDefaultItem,
      ResumeEducationSliceVariation,
      ResumeEducationSliceDefault,
      ResumeListSlice,
      ResumeListSliceDefaultPrimary,
      ResumeListSliceDefaultItem,
      ResumeListSliceVariation,
      ResumeListSliceDefault,
      ResumeWorkHistorySlice,
      ResumeWorkHistorySliceDefaultPrimary,
      ResumeWorkHistorySliceDefaultItem,
      ResumeWorkHistorySliceVariation,
      ResumeWorkHistorySliceDefault,
      ResumeWorkHistoryCondensedSlice,
      ResumeWorkHistoryCondensedSliceDefaultPrimary,
      ResumeWorkHistoryCondensedSliceDefaultItem,
      ResumeWorkHistoryCondensedSliceVariation,
      ResumeWorkHistoryCondensedSliceDefault,
      WorkTogetherSlice,
      WorkTogetherSliceDefaultPrimary,
      WorkTogetherSliceVariation,
      WorkTogetherSliceDefault,
    };
  }
}
