// Code generated by prismic-ts-codegen. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

// Resume Slice Types
export type ResumeWorkHistorySlice = prismic.Slice<
  'resume_work_history',
  Record<string, never>,
  {
    company: prismic.KeyTextField;
    position: prismic.KeyTextField;
    start_date: prismic.DateField;
    end_date: prismic.DateField;
    description: prismic.RichTextField;
    location: prismic.KeyTextField;
  }
>;

export type ResumeEducationSlice = prismic.Slice<
  'resume_education',
  Record<string, never>,
  {
    institution: prismic.KeyTextField;
    degree: prismic.KeyTextField;
    field_of_study: prismic.KeyTextField;
    start_date: prismic.DateField;
    end_date: prismic.DateField;
    description: prismic.RichTextField;
  }
>;

export type ResumeWorkHistoryCondensedSlice = prismic.Slice<
  'resume_work_history_condensed',
  Record<string, never>,
  {
    company: prismic.KeyTextField;
    position: prismic.KeyTextField;
    start_date: prismic.DateField;
    end_date: prismic.DateField;
    description: prismic.RichTextField;
  }
>;

export type WorkTogetherSlice = prismic.Slice<
  'work_together',
  Record<string, never>,
  {
    title: prismic.RichTextField;
    description: prismic.RichTextField;
    cta_text: prismic.KeyTextField;
    cta_link: prismic.LinkField;
  }
>;

export type ResumeContentSlice = prismic.Slice<
  'resume_content',
  Record<string, never>,
  {
    title: prismic.RichTextField;
    content: prismic.RichTextField;
  }
>;

export type ResumeListSlice = prismic.Slice<
  'resume_list',
  Record<string, never>,
  any
>;

export type ResumeAwardsSlice = prismic.Slice<
  'resume_awards',
  Record<string, never>,
  any
>;

// Document Types
export type HomepageDocument = prismic.PrismicDocumentWithUID<
  {
    title: prismic.RichTextField;
    description: prismic.RichTextField;
    hero_image: prismic.ImageField;
    body: prismic.SliceZone;
  },
  'homepage',
  'en'
>;

export type ResumeDocument = prismic.PrismicDocumentWithUID<
  {
    name: prismic.KeyTextField;
    title: prismic.KeyTextField;
    email: prismic.KeyTextField;
    phone: prismic.KeyTextField;
    location: prismic.KeyTextField;
    summary: prismic.RichTextField;
    body: prismic.SliceZone;
  },
  'resume',
  'en'
>;

declare module '@prismicio/client' {
  namespace Content {
    export type {
      HomepageDocument,
      ResumeDocument,
      ResumeWorkHistorySlice,
      ResumeEducationSlice,
      ResumeWorkHistoryCondensedSlice,
      WorkTogetherSlice,
      ResumeContentSlice,
      ResumeListSlice,
      ResumeAwardsSlice,
    };
  }
}
