// Code generated by Slice Machine. DO NOT EDIT.

import Links from './Links';
import ResumeAwards from './ResumeAwards';
import ResumeContent from './ResumeContent';
import ResumeEducation from './ResumeEducation';
import ResumeList from './ResumeList';
import ResumeWorkHistory from './ResumeWorkHistory';
import ResumeWorkHistoryCondensed from './ResumeWorkHistoryCondensed';
import WorkTogether from './WorkTogether';
import CodeBlock from './CodeBlock';
import Words from './Words';
import Embed from './Embed';
import Gallery from './Gallery';

export const components = {
  Links: Links,
  ResumeAwards: ResumeAwards,
  ResumeContent: ResumeContent,
  ResumeEducation: ResumeEducation,
  ResumeList: ResumeList,
  ResumeWorkHistory: ResumeWorkHistory,
  ResumeWorkHistoryCondensed: ResumeWorkHistoryCondensed,
  WorkTogether: WorkTogether,
  code_block: CodeBlock,
  content: Words,
  embed: Embed,
  gallery: Gallery,
};
