// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic';

export const components = {
  Links: dynamic(() => import('./Links')),
  ResumeAwards: dynamic(() => import('./ResumeAwards')),
  ResumeContent: dynamic(() => import('./ResumeContent')),
  ResumeEducation: dynamic(() => import('./ResumeEducation')),
  ResumeList: dynamic(() => import('./ResumeList')),
  ResumeWorkHistory: dynamic(() => import('./ResumeWorkHistory')),
  ResumeWorkHistoryCondensed: dynamic(
    () => import('./ResumeWorkHistoryCondensed'),
  ),
  WorkTogether: dynamic(() => import('./WorkTogether')),
  content: dynamic(() => import('./Words')),
  gallery: dynamic(() => import('./Gallery')),
};
