// Code generated by prismic-ts-codegen. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };


type PickContentRelationshipFieldData<
	TRelationship extends prismic.CustomTypeModelFetchCustomTypeLevel1 | prismic.CustomTypeModelFetchCustomTypeLevel2 | prismic.CustomTypeModelFetchGroupLevel1 | prismic.CustomTypeModelFetchGroupLevel2,
	TData extends Record<string, prismic.AnyRegularField | prismic.GroupField | prismic.NestedGroupField | prismic.SliceZone>,
	TLang extends string
> = |
	// Content relationship fields
	{
		[TSubRelationship in Extract<
			TRelationship["fields"][number], prismic.CustomTypeModelFetchContentRelationshipLevel1
		> as TSubRelationship["id"]]:
			ContentRelationshipFieldWithData<TSubRelationship["customtypes"], TLang>;
	} &
	// Group
	{
		[TGroup in Extract<
			TRelationship["fields"][number], prismic.CustomTypeModelFetchGroupLevel1 | prismic.CustomTypeModelFetchGroupLevel2
		> as TGroup["id"]]:
			TData[TGroup["id"]] extends prismic.GroupField<infer TGroupData>
				? prismic.GroupField<PickContentRelationshipFieldData<TGroup, TGroupData, TLang>>
				: never
	} &
	// Other fields
	{
		[TFieldKey in Extract<TRelationship["fields"][number], string>]:
			TFieldKey extends keyof TData ? TData[TFieldKey] : never;
	};

type ContentRelationshipFieldWithData<
	TCustomType extends readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[] | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
	TLang extends string = string
> = {
	[ID in Exclude<TCustomType[number], string>["id"]]:
		prismic.ContentRelationshipField<
			ID,
			TLang,
			PickContentRelationshipFieldData<
				Extract<TCustomType[number], { id: ID }>,
				Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
				TLang
			>
		>
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Content for Employers and Recruiters documents
 */
interface EmployersRecruitersDocumentData {
	/**
	 * title field in *Employers and Recruiters*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: employers_recruiters.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
	
	/**
	 * body field in *Employers and Recruiters*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: employers_recruiters.body
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	body: prismic.RichTextField;
}

/**
 * Employers and Recruiters document from Prismic
 *
 * - **API ID**: `employers_recruiters`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EmployersRecruitersDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<EmployersRecruitersDocumentData>, "employers_recruiters", Lang>;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
	/**
	 * Introduction field in *Homepage*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.introduction
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	introduction: prismic.RichTextField;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<HomepageDocumentData>, "homepage", Lang>;

/**
 * Primary content in *Resume → Slice zone → Links → Primary*
 */
export interface ResumeDocumentDataBodyLinksSlicePrimary {
	/**
	 * Title field in *Resume → Slice zone → Links → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: resume.body[].links.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
}

/**
 * Item content in *Resume → Slice zone → Links → Items*
 */
export interface ResumeDocumentDataBodyLinksSliceItem {
	/**
	 * label field in *Resume → Slice zone → Links → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: resume.body[].links.items.label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label: prismic.KeyTextField;
	
	/**
	 * link field in *Resume → Slice zone → Links → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: resume.body[].links.items.link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
	
	/**
	 * type field in *Resume → Slice zone → Links → Items*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: resume.body[].links.items.type
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	type: prismic.SelectField<"website" | "phone" | "email" | "document" | "external" | "project" | "user" | "user_plus" | "users" | "code" | "command">;
}

/**
 * Slice for *Resume → Slice zone*
 */
export type ResumeDocumentDataBodyLinksSlice = prismic.Slice<"links", Simplify<ResumeDocumentDataBodyLinksSlicePrimary>, Simplify<ResumeDocumentDataBodyLinksSliceItem>>

/**
 * Primary content in *Resume → Slice zone → Resume Content → Primary*
 */
export interface ResumeDocumentDataBodyResumeContentSlicePrimary {
	/**
	 * Title field in *Resume → Slice zone → Resume Content → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: resume.body[].resume_content.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
	
	/**
	 * Content field in *Resume → Slice zone → Resume Content → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: resume.body[].resume_content.primary.content
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	content: prismic.RichTextField;
	
	/**
	 * Large Copy field in *Resume → Slice zone → Resume Content → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: resume.body[].resume_content.primary.large_copy
	 * - **Documentation**: https://prismic.io/docs/fields/boolean
	 */
	large_copy: prismic.BooleanField;
	
	/**
	 * Include in Print field in *Resume → Slice zone → Resume Content → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: resume.body[].resume_content.primary.include_in_print
	 * - **Documentation**: https://prismic.io/docs/fields/boolean
	 */
	include_in_print: prismic.BooleanField;
}

/**
 * Slice for *Resume → Slice zone*
 */
export type ResumeDocumentDataBodyResumeContentSlice = prismic.Slice<"resume_content", Simplify<ResumeDocumentDataBodyResumeContentSlicePrimary>, never>

/**
 * Primary content in *Resume → Slice zone → Resume List → Primary*
 */
export interface ResumeDocumentDataBodyResumeListSlicePrimary {
	/**
	 * Title field in *Resume → Slice zone → Resume List → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: resume.body[].resume_list.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
	
	/**
	 * Content field in *Resume → Slice zone → Resume List → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: resume.body[].resume_list.primary.content
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	content: prismic.RichTextField;
}

/**
 * Item content in *Resume → Slice zone → Resume List → Items*
 */
export interface ResumeDocumentDataBodyResumeListSliceItem {
	/**
	 * Content field in *Resume → Slice zone → Resume List → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: resume.body[].resume_list.items.content
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	content: prismic.RichTextField;
}

/**
 * Slice for *Resume → Slice zone*
 */
export type ResumeDocumentDataBodyResumeListSlice = prismic.Slice<"resume_list", Simplify<ResumeDocumentDataBodyResumeListSlicePrimary>, Simplify<ResumeDocumentDataBodyResumeListSliceItem>>

/**
 * Primary content in *Resume → Slice zone → Resume Work History → Primary*
 */
export interface ResumeDocumentDataBodyResumeWorkHistorySlicePrimary {
	/**
	 * Title field in *Resume → Slice zone → Resume Work History → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: resume.body[].resume_work_history.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
}

/**
 * Item content in *Resume → Slice zone → Resume Work History → Items*
 */
export interface ResumeDocumentDataBodyResumeWorkHistorySliceItem {
	/**
	 * Company Logo field in *Resume → Slice zone → Resume Work History → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: resume.body[].resume_work_history.items.company_logo
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	company_logo: prismic.ImageField<never>;
	
	/**
	 * Company field in *Resume → Slice zone → Resume Work History → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: resume.body[].resume_work_history.items.company
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	company: prismic.RichTextField;
	
	/**
	 * Job Title field in *Resume → Slice zone → Resume Work History → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: resume.body[].resume_work_history.items.job_title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	job_title: prismic.RichTextField;
	
	/**
	 * Content field in *Resume → Slice zone → Resume Work History → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: resume.body[].resume_work_history.items.content
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	content: prismic.RichTextField;
	
	/**
	 * Present Role field in *Resume → Slice zone → Resume Work History → Items*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: resume.body[].resume_work_history.items.present_role
	 * - **Documentation**: https://prismic.io/docs/fields/boolean
	 */
	present_role: prismic.BooleanField;
	
	/**
	 * Start Date field in *Resume → Slice zone → Resume Work History → Items*
	 *
	 * - **Field Type**: Date
	 * - **Placeholder**: *None*
	 * - **API ID Path**: resume.body[].resume_work_history.items.start_date
	 * - **Documentation**: https://prismic.io/docs/fields/date
	 */
	start_date: prismic.DateField;
	
	/**
	 * End Date field in *Resume → Slice zone → Resume Work History → Items*
	 *
	 * - **Field Type**: Date
	 * - **Placeholder**: *None*
	 * - **API ID Path**: resume.body[].resume_work_history.items.end_date
	 * - **Documentation**: https://prismic.io/docs/fields/date
	 */
	end_date: prismic.DateField;
	
	/**
	 * Company Website field in *Resume → Slice zone → Resume Work History → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: resume.body[].resume_work_history.items.company_website
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	company_website: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
	
	/**
	 * Keywords field in *Resume → Slice zone → Resume Work History → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: resume.body[].resume_work_history.items.keywords
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	keywords: prismic.KeyTextField;
}

/**
 * Slice for *Resume → Slice zone*
 */
export type ResumeDocumentDataBodyResumeWorkHistorySlice = prismic.Slice<"resume_work_history", Simplify<ResumeDocumentDataBodyResumeWorkHistorySlicePrimary>, Simplify<ResumeDocumentDataBodyResumeWorkHistorySliceItem>>

/**
 * Primary content in *Resume → Slice zone → Resume Work History Condensed → Primary*
 */
export interface ResumeDocumentDataBodyResumeWorkHistoryCondensedSlicePrimary {
	/**
	 * Title field in *Resume → Slice zone → Resume Work History Condensed → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: resume.body[].resume_work_history_condensed.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
}

/**
 * Item content in *Resume → Slice zone → Resume Work History Condensed → Items*
 */
export interface ResumeDocumentDataBodyResumeWorkHistoryCondensedSliceItem {
	/**
	 * Company field in *Resume → Slice zone → Resume Work History Condensed → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: resume.body[].resume_work_history_condensed.items.company
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	company: prismic.RichTextField;
	
	/**
	 * Job Title field in *Resume → Slice zone → Resume Work History Condensed → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: resume.body[].resume_work_history_condensed.items.job_title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	job_title: prismic.RichTextField;
	
	/**
	 * Start Date field in *Resume → Slice zone → Resume Work History Condensed → Items*
	 *
	 * - **Field Type**: Date
	 * - **Placeholder**: *None*
	 * - **API ID Path**: resume.body[].resume_work_history_condensed.items.start_date
	 * - **Documentation**: https://prismic.io/docs/fields/date
	 */
	start_date: prismic.DateField;
	
	/**
	 * End Date field in *Resume → Slice zone → Resume Work History Condensed → Items*
	 *
	 * - **Field Type**: Date
	 * - **Placeholder**: *None*
	 * - **API ID Path**: resume.body[].resume_work_history_condensed.items.end_date
	 * - **Documentation**: https://prismic.io/docs/fields/date
	 */
	end_date: prismic.DateField;
}

/**
 * Slice for *Resume → Slice zone*
 */
export type ResumeDocumentDataBodyResumeWorkHistoryCondensedSlice = prismic.Slice<"resume_work_history_condensed", Simplify<ResumeDocumentDataBodyResumeWorkHistoryCondensedSlicePrimary>, Simplify<ResumeDocumentDataBodyResumeWorkHistoryCondensedSliceItem>>

/**
 * Primary content in *Resume → Slice zone → Resume Awards → Primary*
 */
export interface ResumeDocumentDataBodyResumeAwardsSlicePrimary {
	/**
	 * Title field in *Resume → Slice zone → Resume Awards → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: resume.body[].resume_awards.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
}

/**
 * Item content in *Resume → Slice zone → Resume Awards → Items*
 */
export interface ResumeDocumentDataBodyResumeAwardsSliceItem {
	/**
	 * Title field in *Resume → Slice zone → Resume Awards → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: resume.body[].resume_awards.items.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
	
	/**
	 * Dates field in *Resume → Slice zone → Resume Awards → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: resume.body[].resume_awards.items.dates
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	dates: prismic.KeyTextField;
}

/**
 * Slice for *Resume → Slice zone*
 */
export type ResumeDocumentDataBodyResumeAwardsSlice = prismic.Slice<"resume_awards", Simplify<ResumeDocumentDataBodyResumeAwardsSlicePrimary>, Simplify<ResumeDocumentDataBodyResumeAwardsSliceItem>>

/**
 * Primary content in *Resume → Slice zone → Work Together → Primary*
 */
export interface ResumeDocumentDataBodyWorkTogetherSlicePrimary {
	/**
	 * Title field in *Resume → Slice zone → Work Together → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: resume.body[].work_together.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
	
	/**
	 * Body: Yes field in *Resume → Slice zone → Work Together → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: resume.body[].work_together.primary.body_yes
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	body_yes: prismic.RichTextField;
	
	/**
	 * Body: No field in *Resume → Slice zone → Work Together → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: resume.body[].work_together.primary.body_no
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	body_no: prismic.RichTextField;
	
	/**
	 * note field in *Resume → Slice zone → Work Together → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: resume.body[].work_together.primary.note
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	note: prismic.RichTextField;
}

/**
 * Slice for *Resume → Slice zone*
 */
export type ResumeDocumentDataBodyWorkTogetherSlice = prismic.Slice<"work_together", Simplify<ResumeDocumentDataBodyWorkTogetherSlicePrimary>, never>

/**
 * Primary content in *Resume → Slice zone → Resume Education → Primary*
 */
export interface ResumeDocumentDataBodyResumeEducationSlicePrimary {
	/**
	 * Title field in *Resume → Slice zone → Resume Education → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: resume.body[].resume_education.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
}

/**
 * Item content in *Resume → Slice zone → Resume Education → Items*
 */
export interface ResumeDocumentDataBodyResumeEducationSliceItem {
	/**
	 * Institution field in *Resume → Slice zone → Resume Education → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: resume.body[].resume_education.items.institution
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	institution: prismic.RichTextField;
	
	/**
	 * Copy field in *Resume → Slice zone → Resume Education → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: resume.body[].resume_education.items.copy
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	copy: prismic.RichTextField;
	
	/**
	 * Start Date field in *Resume → Slice zone → Resume Education → Items*
	 *
	 * - **Field Type**: Date
	 * - **Placeholder**: *None*
	 * - **API ID Path**: resume.body[].resume_education.items.start_date
	 * - **Documentation**: https://prismic.io/docs/fields/date
	 */
	start_date: prismic.DateField;
	
	/**
	 * End Date field in *Resume → Slice zone → Resume Education → Items*
	 *
	 * - **Field Type**: Date
	 * - **Placeholder**: *None*
	 * - **API ID Path**: resume.body[].resume_education.items.end_date
	 * - **Documentation**: https://prismic.io/docs/fields/date
	 */
	end_date: prismic.DateField;
}

/**
 * Slice for *Resume → Slice zone*
 */
export type ResumeDocumentDataBodyResumeEducationSlice = prismic.Slice<"resume_education", Simplify<ResumeDocumentDataBodyResumeEducationSlicePrimary>, Simplify<ResumeDocumentDataBodyResumeEducationSliceItem>>

type ResumeDocumentDataBodySlice = ResumeDocumentDataBodyLinksSlice | ResumeDocumentDataBodyResumeContentSlice | ResumeDocumentDataBodyResumeListSlice | ResumeDocumentDataBodyResumeWorkHistorySlice | ResumeDocumentDataBodyResumeWorkHistoryCondensedSlice | ResumeDocumentDataBodyResumeAwardsSlice | ResumeDocumentDataBodyWorkTogetherSlice | ResumeDocumentDataBodyResumeEducationSlice

/**
 * Content for Resume documents
 */
interface ResumeDocumentData {
	/**
	 * Name field in *Resume*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: resume.name
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	name: prismic.RichTextField;
	
	/**
	 * Current Job Title field in *Resume*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: resume.current_job_title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	current_job_title: prismic.RichTextField;
	
	/**
	 * Current Role Location field in *Resume*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: resume.current_role_location
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	current_role_location: prismic.RichTextField;
	
	/**
	 * Slice zone field in *Resume*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: resume.body[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	body: prismic.SliceZone<ResumeDocumentDataBodySlice>;
}

/**
 * Resume document from Prismic
 *
 * - **API ID**: `resume`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ResumeDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<ResumeDocumentData>, "resume", Lang>;

export type AllDocumentTypes = EmployersRecruitersDocument | HomepageDocument | ResumeDocument;

declare module "@prismicio/client" {
	interface CreateClient {
		(repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
	}
	
	interface CreateWriteClient {
		(repositoryNameOrEndpoint: string, options: prismic.WriteClientConfig): prismic.WriteClient<AllDocumentTypes>;
	}
	
	interface CreateMigration {
		(): prismic.Migration<AllDocumentTypes>;
	}
	
	namespace Content {
		export type {
			EmployersRecruitersDocument,
			EmployersRecruitersDocumentData,
			HomepageDocument,
			HomepageDocumentData,
			ResumeDocument,
			ResumeDocumentData,
			ResumeDocumentDataBodyLinksSlicePrimary,
			ResumeDocumentDataBodyLinksSliceItem,
			ResumeDocumentDataBodyResumeContentSlicePrimary,
			ResumeDocumentDataBodyResumeListSlicePrimary,
			ResumeDocumentDataBodyResumeListSliceItem,
			ResumeDocumentDataBodyResumeWorkHistorySlicePrimary,
			ResumeDocumentDataBodyResumeWorkHistorySliceItem,
			ResumeDocumentDataBodyResumeWorkHistoryCondensedSlicePrimary,
			ResumeDocumentDataBodyResumeWorkHistoryCondensedSliceItem,
			ResumeDocumentDataBodyResumeAwardsSlicePrimary,
			ResumeDocumentDataBodyResumeAwardsSliceItem,
			ResumeDocumentDataBodyWorkTogetherSlicePrimary,
			ResumeDocumentDataBodyResumeEducationSlicePrimary,
			ResumeDocumentDataBodyResumeEducationSliceItem,
			ResumeDocumentDataBodySlice,
			AllDocumentTypes
		}
	}
}