export const GameEvents = {
    MOUSE_DOWN: 'MOUSE_DOWN',
    MOUSE_UP: 'MOUSE_UP',
    MOUSE_MOVE: 'MOUSE_MOVE',

    RESET_PLAYER_STATE: 'RESET_PLAYER_STATE',
    PLAYER_HIT: 'PLAYER_HIT',
    PLAYER_DIED: 'PLAYER_DIED',

    SHIELD_HIT: 'SHIELD_HIT',
    SHIELD_DOWN: 'SHIELD_DOWN',

    GAME_IDLE: 'GAME_IDLE',
    GAME_PLAYING: 'GAME_PLAYING',
    GAME_PAUSED: 'GAME_PAUSED,',
};
