export const GameEvents = {
    MOUSE_DOWN: 'MOUSE_DOWN',
    MOUSE_UP: 'MOUSE_UP',
    MOUSE_MOVE: 'MOUSE_MOVE',

    PLAYER_HIT: 'PLAYER_HIT',
    PLAYER_DIED: 'PLAYER_DIED',

    GAME_IDLE: 'GAME_IDLE',
    GAME_PLAYING: 'GAME_PLAYING',
    GAME_PAUSED: 'GAME_PAUSED,',
};
