export const actionTypes = {
    // Player
    RESET_PLAYER_STATE_AFTER_DEATH: 'RESET_PLAYER_STATE_AFTER_DEATH',
    PLAYER_HIT: 'PLAYER_HIT',
    PLAYER_SHIELD_HIT: 'PLAYER_SHIELD_HIT',
    RESET_GAME_STATE: 'RESET_GAME_STATE',

    // Events
    POINTER_DOWN: 'POINTER_DOWN',
    POINTER_UP: 'POINTER_UP',

    // Score
    ENEMY_KILLED: 'ENEMY_KILLED',
};
