export const actionTypes = {
    // Player
    RESET_PLAYER_STATE_AFTER_DEATH: 'RESET_PLAYER_STATE_AFTER_DEATH',
    PLAYER_HIT: 'PLAYER_HIT',
    PLAYER_SHIELD_HIT: 'PLAYER_SHIELD_HIT',
    RESET_GAME_STATE: 'RESET_GAME_STATE',

    // Events
    POINTER_DOWN: 'POINTER_DOWN',
    POINTER_UP: 'POINTER_UP',
    ARROW_LEFT_DOWN: 'ARROW_LEFT_DOWN',
    ARROW_LEFT_UP: 'ARROW_LEFT_UP',
    ARROW_RIGHT_DOWN: 'ARROW_RIGHT_DOWN',
    ARROW_RIGHT_UP: 'ARROW_RIGHT_UP',

    // Score
    ENEMY_KILLED: 'ENEMY_KILLED',

    // Levels
    NEXT_LEVEL: 'NEXT_LEVEL',
};
