export const actionTypes = {
    // Player
    RESET_PLAYER_STATE_AFTER_DEATH: 'RESET_PLAYER_STATE_AFTER_DEATH',
    PLAYER_HIT: 'PLAYER_HIT',
    PLAYER_SHIELD_HIT: 'PLAYER_SHIELD_HIT',
    RESET_GAME_STATE: 'RESET_GAME_STATE',
    WEAPON_POWER_UP: 'WEAPON_POWER_UP',

    // Score
    ENEMY_KILLED: 'ENEMY_KILLED',

    // Levels
    NEXT_LEVEL: 'NEXT_LEVEL',
};
