const eventTypes = {
  // Events
  POINTER_DOWN: 'POINTER_DOWN',
  POINTER_UP: 'POINTER_UP',
  ARROW_LEFT_DOWN: 'ARROW_LEFT_DOWN',
  ARROW_LEFT_UP: 'ARROW_LEFT_UP',
  ARROW_RIGHT_DOWN: 'ARROW_RIGHT_DOWN',
  ARROW_RIGHT_UP: 'ARROW_RIGHT_UP',
};

export default eventTypes;
